name: "Java CI with Maven - Test and package"

on: 
  pull_request:
    branches:
      - main

jobs: 
  JavaTest:
    name: JavaTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: '21'
      - run: java --version
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
      run : mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
      


